services:

  Ivom.Invoices.domain.InvoiceRepository:
    class: ../../../../Contexts/Ivom/Invoices/infrastructure/persistence/InMemoryInvoiceRepository
    arguments: []

  Ivom.Invoices.application.CreateInvoicePdfOnInvoiceCreatedDomainEventHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/CreateInvoicePdfOnInvoiceCreatedDomainEventHandler
    arguments: []

  Shared.domain.DomainEventBus:
    class: ../../../../Contexts/Shared/infrastructure/DomainEventBusImpl
    arguments: [
      '@Ivom.Invoices.application.CreateInvoicePdfOnInvoiceCreatedDomainEventHandler',
    ]

  Ivom.Invoices.application.CreateInvoiceCommandHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/CreateInvoiceCommandHandler
    arguments: ['@Shared.domain.DomainEventBus', '@Ivom.Invoices.domain.InvoiceRepository']

  Ivom.Invoices.application.SearchInvoicesByCriteriaQueryHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/SearchInvoicesByCriteriaQueryHandler
    arguments: []

  Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBusImpl
    arguments: [
      '@Ivom.Invoices.application.CreateInvoiceCommandHandler'
    ]

  Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBusImpl
    arguments: [
      '@Ivom.Invoices.application.SearchInvoicesByCriteriaQueryHandler'
    ]

  Apps.ivom.controllers.StatusGetController:
    class: ../controllers/StatusGetController
    arguments: []

  Apps.ivom.controllers.InvoicePutController:
    class: ../controllers/InvoicePutController
    arguments: ['@Shared.domain.CommandBus']

  Apps.ivom.controllers.InvoicesGetController:
    class: ../controllers/InvoicesGetController
    arguments: ['@Shared.domain.QueryBus']
