services:

  Ivom.Invoices.application.CreateInvoiceCommandHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/CreateInvoiceCommandHandler
    arguments: ['@Shared.domain.EventBus']

  Ivom.Invoices.application.SearchInvoicesByCriteriaQueryHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/SearchInvoicesByCriteriaQueryHandler
    arguments: []

  Ivom.Invoices.application.CreateInvoicePdfOnInvoiceCreatedEventHandler:
    class: ../../../../Contexts/Ivom/Invoices/application/CreateInvoicePdfOnInvoiceCreatedEventHandler
    arguments: []

  Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBusImpl
    arguments: [
      '@service_container',
      [
        {
          commandClassName: 'CreateInvoiceCommand',
          handlerContainerServiceId: 'Ivom.Invoices.application.CreateInvoiceCommandHandler'
        }
      ]
    ]

  Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBusImpl
    arguments: [
      '@service_container',
      [
        {
          queryClassName: 'SearchInvoicesByCriteriaQuery',
          handlerContainerServiceId: 'Ivom.Invoices.application.SearchInvoicesByCriteriaQueryHandler'
        }
      ]
    ]

  Shared.domain.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBusImpl
    arguments: [
      '@service_container',
      [
        {
          eventsClassNames: ['InvoiceCreatedDomainEvent'],
          handlerContainerServiceId: 'Ivom.Invoices.application.CreateInvoicePdfOnInvoiceCreatedEventHandler'
        }
      ]
    ]

  Apps.ivom.controllers.StatusGetController:
    class: ../controllers/StatusGetController
    arguments: []

  Apps.ivom.controllers.InvoicePutController:
    class: ../controllers/InvoicePutController
    arguments: ['@Shared.domain.CommandBus']

  Apps.ivom.controllers.InvoicesGetController:
    class: ../controllers/InvoicesGetController
    arguments: ['@Shared.domain.QueryBus']
